//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodIdentifier.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoodIdentifier.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutToolbarItemText {
            get {
                return ResourceManager.GetString("AboutToolbarItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string AboutViewPageAppNameTitleLabel {
            get {
                return ResourceManager.GetString("AboutViewPageAppNameTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string AboutViewPageAppVersionTitleLabel {
            get {
                return ResourceManager.GetString("AboutViewPageAppVersionTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Info:
        ///Model: {0}
        ///Manufacturer: {1}
        ///OS Version: {2}
        ///Platform: {3}
        ///
        ///App Info:
        ///Version: {4}
        ///Build:{5}
        ///
        ///- - - - -.
        /// </summary>
        internal static string AboutViewPageBodyMail {
            get {
                return ResourceManager.GetString("AboutViewPageBodyMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With the help of the Microsoft Cognitive Services Custom Vision, this app allows you to analyze and classify photos and images.
        ///
        ///The aim is to recognize and distinguish different food dishes, such as pizza, hot dogs or even salad. The result is shown with the indication of a probability after the analysis.
        ///
        ///The analysis is done online, so that an internet connection is necessary. Similarly, the app currently only work with endpoints, which are located in northern Europe..
        /// </summary>
        internal static string AboutViewPageInfoLabel {
            get {
                return ResourceManager.GetString("AboutViewPageInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string AboutViewPageInfoTitleLabel {
            get {
                return ResourceManager.GetString("AboutViewPageInfoTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail to the developer.
        /// </summary>
        internal static string AboutViewPageMailButton {
            get {
                return ResourceManager.GetString("AboutViewPageMailButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback &apos;Food Identifier&apos;.
        /// </summary>
        internal static string AboutViewPageSubjectMail {
            get {
                return ResourceManager.GetString("AboutViewPageSubjectMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutViewPageTitle {
            get {
                return ResourceManager.GetString("AboutViewPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apps@tsjdev-apps.de.
        /// </summary>
        internal static string AboutViewPageToMail {
            get {
                return ResourceManager.GetString("AboutViewPageToMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        internal static string AboutViewPageTwitterButton {
            get {
                return ResourceManager.GetString("AboutViewPageTwitterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://twitter.com/tsjdevapps.
        /// </summary>
        internal static string AboutViewPageTwitterLink {
            get {
                return ResourceManager.GetString("AboutViewPageTwitterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string AboutViewPageWebsiteButton {
            get {
                return ResourceManager.GetString("AboutViewPageWebsiteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.tsjdev-apps.de.
        /// </summary>
        internal static string AboutViewPageWebsiteLink {
            get {
                return ResourceManager.GetString("AboutViewPageWebsiteLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food Identifier.
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string DialogButtonOk {
            get {
                return ResourceManager.GetString("DialogButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong, please try again later.
        ///
        ///Details: {0}.
        /// </summary>
        internal static string ErrorDialogMessage {
            get {
                return ResourceManager.GetString("ErrorDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorDialogTitle {
            get {
                return ResourceManager.GetString("ErrorDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string LoadingViewInfoLabel {
            get {
                return ResourceManager.GetString("LoadingViewInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please take a picture or pick a file to start the food prediction..
        /// </summary>
        internal static string MainViewNoPictureSelectedInfoLabel {
            get {
                return ResourceManager.GetString("MainViewNoPictureSelectedInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food Identifier.
        /// </summary>
        internal static string MainViewPageTitle {
            get {
                return ResourceManager.GetString("MainViewPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string ResultDialogTitle {
            get {
                return ResourceManager.GetString("ResultDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I analyzed the picture and unfortunately I&apos;m not sure at all. Please try again with another photo..
        /// </summary>
        internal static string ResultErrorMessage {
            get {
                return ResourceManager.GetString("ResultErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have analyzed the picture and I am {0}% sure:
        ///{1}.
        /// </summary>
        internal static string ResultSuccessMessage {
            get {
                return ResourceManager.GetString("ResultSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint.
        /// </summary>
        internal static string SettingsEndpointPlaceholder {
            get {
                return ResourceManager.GetString("SettingsEndpointPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iteration Name.
        /// </summary>
        internal static string SettingsIterationNamePlaceholder {
            get {
                return ResourceManager.GetString("SettingsIterationNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prediction Key.
        /// </summary>
        internal static string SettingsPredictionKeyPlaceholder {
            get {
                return ResourceManager.GetString("SettingsPredictionKeyPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project ID.
        /// </summary>
        internal static string SettingsProjectIdPlaceholder {
            get {
                return ResourceManager.GetString("SettingsProjectIdPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsToolbarItemText {
            get {
                return ResourceManager.GetString("SettingsToolbarItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsViewPageTitle {
            get {
                return ResourceManager.GetString("SettingsViewPageTitle", resourceCulture);
            }
        }
    }
}
